package InformeMedico;

import javax.swing.WindowConstants;

/**
 *
 * @author Vulture
 */
public class DatosPaciente extends javax.swing.JFrame {

    Paciente paciente;
    /**
     * Creates new form DatosPersonales
     */
    public DatosPaciente(Paciente paciente) {
        initComponents();
        this.paciente=paciente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        personalesPanel = new javax.swing.JPanel();
        tituloPersonalesLabel = new javax.swing.JLabel();
        apellidosLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        apellidosTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        nacimientoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idiomasList = new javax.swing.JList<>();
        idiomaLabel = new javax.swing.JLabel();
        MasculinoRadioButton = new javax.swing.JRadioButton();
        femeninoRadioButton = new javax.swing.JRadioButton();
        sexoLabel = new javax.swing.JLabel();
        nacimientoSpinner = new javax.swing.JSpinner();
        contactoPanel = new javax.swing.JPanel();
        tituloContactoLabe7 = new javax.swing.JLabel();
        residenciaLabel = new javax.swing.JLabel();
        trabajoLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        residenciaTextField = new javax.swing.JTextField();
        trabajoTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        correoTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        conviveLabel = new javax.swing.JLabel();
        viviendaLabel = new javax.swing.JLabel();
        macotas = new javax.swing.JLabel();
        conviveSpinner = new javax.swing.JSpinner();
        pisoRadioButton = new javax.swing.JRadioButton();
        adosadoRadioButton = new javax.swing.JRadioButton();
        chaletRadioButton = new javax.swing.JRadioButton();
        tituloHogarLabel = new javax.swing.JLabel();
        mascotasCheckBox = new javax.swing.JCheckBox();
        mascotasTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        tituloTrabajoLabel = new javax.swing.JLabel();
        empleoLabel = new javax.swing.JLabel();
        empleoTextField = new javax.swing.JTextField();
        añosLabel = new javax.swing.JLabel();
        empleosRiesgoLabel = new javax.swing.JLabel();
        empleosRiesgoTextField = new javax.swing.JTextField();
        añosSpinner = new javax.swing.JSpinner();
        borrarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tituloPersonalesLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tituloPersonalesLabel.setText("DATOS PERSONALES DEL PACIENTE");

        apellidosLabel.setText("Apellidos:");

        nombreLabel.setText("Nombre:");

        apellidosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosTextFieldActionPerformed(evt);
            }
        });

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        nacimientoLabel.setText("Fecha Nacimeinto:");

        idiomasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Español", "Ingles", "Frances", "Aleman", "Ruso", "Chino", "Otros" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(idiomasList);

        idiomaLabel.setText("Idioma:");

        buttonGroup1.add(MasculinoRadioButton);
        MasculinoRadioButton.setText("Masculino");

        buttonGroup1.add(femeninoRadioButton);
        femeninoRadioButton.setText("Femenino");

        sexoLabel.setText("Sexo:");

        nacimientoSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_YEAR));

        javax.swing.GroupLayout personalesPanelLayout = new javax.swing.GroupLayout(personalesPanel);
        personalesPanel.setLayout(personalesPanelLayout);
        personalesPanelLayout.setHorizontalGroup(
            personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloPersonalesLabel)
                    .addGroup(personalesPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apellidosLabel)
                            .addComponent(nombreLabel)
                            .addComponent(nacimientoLabel)
                            .addComponent(idiomaLabel)
                            .addComponent(sexoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalesPanelLayout.createSequentialGroup()
                                .addComponent(MasculinoRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(femeninoRadioButton))
                            .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(apellidosTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(nombreTextField))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nacimientoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        personalesPanelLayout.setVerticalGroup(
            personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPersonalesLabel)
                .addGap(26, 26, 26)
                .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacimientoLabel)
                    .addComponent(nacimientoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalesPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(idiomaLabel))
                    .addGroup(personalesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasculinoRadioButton)
                    .addComponent(femeninoRadioButton)
                    .addComponent(sexoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personales", personalesPanel);

        tituloContactoLabe7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tituloContactoLabe7.setText("DATOS DE CONTACTO DEL PACIENTE");

        residenciaLabel.setText("Domicilio De Residencia:");

        trabajoLabel.setText("Domicilio de Trabajo:");

        telefonoLabel.setText("Telefono:");

        correoLabel.setText("Correo Electronico:");

        residenciaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residenciaTextFieldActionPerformed(evt);
            }
        });

        correoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contactoPanelLayout = new javax.swing.GroupLayout(contactoPanel);
        contactoPanel.setLayout(contactoPanelLayout);
        contactoPanelLayout.setHorizontalGroup(
            contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloContactoLabe7)
                    .addGroup(contactoPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefonoLabel)
                            .addComponent(trabajoLabel)
                            .addComponent(residenciaLabel)
                            .addComponent(correoLabel))
                        .addGap(33, 33, 33)
                        .addGroup(contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(residenciaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(trabajoTextField)
                            .addComponent(telefonoTextField)
                            .addComponent(correoTextField))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        contactoPanelLayout.setVerticalGroup(
            contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloContactoLabe7)
                .addGap(37, 37, 37)
                .addGroup(contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(residenciaLabel)
                    .addComponent(residenciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trabajoLabel)
                    .addComponent(trabajoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoLabel)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(contactoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoLabel)
                    .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contacto", contactoPanel);

        conviveLabel.setText("Personas con las que convive:");

        viviendaLabel.setText("Tipo de vivienda:");

        macotas.setText("Mascotas en la vivienda:");

        buttonGroup2.add(pisoRadioButton);
        pisoRadioButton.setText("Piso");
        pisoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisoRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(adosadoRadioButton);
        adosadoRadioButton.setText("Adosado");

        buttonGroup2.add(chaletRadioButton);
        chaletRadioButton.setText("Chalet");
        chaletRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaletRadioButtonActionPerformed(evt);
            }
        });

        tituloHogarLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tituloHogarLabel.setText("DATOS SOBRE EL HOGAR DEL PACIENTE");

        mascotasCheckBox.setText("SI");

        mascotasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascotasTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloHogarLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(conviveLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(conviveSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(macotas)
                                    .addComponent(viviendaLabel))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pisoRadioButton)
                                    .addComponent(mascotasCheckBox))))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(adosadoRadioButton)
                                .addGap(30, 30, 30)
                                .addComponent(chaletRadioButton))
                            .addComponent(mascotasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloHogarLabel)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conviveLabel)
                    .addComponent(conviveSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viviendaLabel)
                    .addComponent(pisoRadioButton)
                    .addComponent(adosadoRadioButton)
                    .addComponent(chaletRadioButton))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(macotas)
                    .addComponent(mascotasCheckBox)
                    .addComponent(mascotasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        jTabbedPane1.addTab("Hogar", jPanel3);

        tituloTrabajoLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tituloTrabajoLabel.setText("DATOS SOBRE EL TRABAJO DEL PACIENTE");

        empleoLabel.setText("Empleo Actual:");

        empleoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleoTextFieldActionPerformed(evt);
            }
        });

        añosLabel.setText("Años e el empleo:");

        empleosRiesgoLabel.setText("Empleos de Riego Pasados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTrabajoLabel)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(añosLabel)
                            .addComponent(empleoLabel)
                            .addComponent(empleosRiesgoLabel))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(añosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empleoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(empleosRiesgoTextField))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloTrabajoLabel)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleoLabel)
                    .addComponent(empleoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añosLabel)
                    .addComponent(añosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleosRiesgoLabel)
                    .addComponent(empleosRiesgoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trabajo", jPanel4);

        borrarButton.setText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(borrarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(guardarButton)
                .addGap(126, 126, 126))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarButton)
                    .addComponent(guardarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void residenciaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residenciaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residenciaTextFieldActionPerformed

    private void correoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTextFieldActionPerformed

    private void pisoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pisoRadioButtonActionPerformed

    private void chaletRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaletRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chaletRadioButtonActionPerformed

    private void mascotasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascotasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mascotasTextFieldActionPerformed

    private void empleoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleoTextFieldActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        GUI gui = new GUI();
        gui.setPaciente(paciente);
        gui.setVisible(true);
        gui.setLocationRelativeTo(null);
        this.dispose();
//        gui.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void apellidosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosTextFieldActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        paciente.setNombre(nombreTextField.getText());
        paciente.setApellidos(apellidosTextField.getText());
        paciente.setFecha(nacimientoSpinner.toString());//provar con value
        paciente.setIdioma(idiomasList.getSelectedValue());
        if(MasculinoRadioButton.isSelected()){
            paciente.setSexo("Masculino");
        }else if(femeninoRadioButton.isSelected()){
            paciente.setSexo("Femenino");
        }else{paciente.setSexo("NoEspecificado");}
        
        paciente.setResidencia(residenciaTextField.getText());
        paciente.setTrabajo(trabajoTextField.getText());
        paciente.setTelefono(telefonoTextField.getText());
        paciente.setCorreo(correoTextField.getText());
        paciente.setPersonasConvive(conviveSpinner.toString());
        if(chaletRadioButton.isSelected()){
            paciente.setTipoVivienda("Chalet");
        }else if(pisoRadioButton.isSelected()){
            paciente.setTipoVivienda("Piso");
        }else if(adosadoRadioButton.isSelected()){
            paciente.setTipoVivienda("Adosado");
        }{paciente.setSexo("NoEspecificado");}
        
        if(mascotasCheckBox.isSelected()){
            paciente.setMacotas(true);
            paciente.setTipoMascota(mascotasTextField.getText());
        }else{paciente.setTipoMascota("-");paciente.setMacotas(false);}
        
        
    }//GEN-LAST:event_guardarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DatosPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DatosPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DatosPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DatosPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DatosPaciente().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton MasculinoRadioButton;
    private javax.swing.JRadioButton adosadoRadioButton;
    private javax.swing.JLabel apellidosLabel;
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JLabel añosLabel;
    private javax.swing.JSpinner añosSpinner;
    private javax.swing.JButton borrarButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton chaletRadioButton;
    private javax.swing.JPanel contactoPanel;
    private javax.swing.JLabel conviveLabel;
    private javax.swing.JSpinner conviveSpinner;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JLabel empleoLabel;
    private javax.swing.JTextField empleoTextField;
    private javax.swing.JLabel empleosRiesgoLabel;
    private javax.swing.JTextField empleosRiesgoTextField;
    private javax.swing.JRadioButton femeninoRadioButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel idiomaLabel;
    private javax.swing.JList<String> idiomasList;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel macotas;
    private javax.swing.JCheckBox mascotasCheckBox;
    private javax.swing.JTextField mascotasTextField;
    private javax.swing.JLabel nacimientoLabel;
    private javax.swing.JSpinner nacimientoSpinner;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPanel personalesPanel;
    private javax.swing.JRadioButton pisoRadioButton;
    private javax.swing.JLabel residenciaLabel;
    private javax.swing.JTextField residenciaTextField;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.JLabel tituloContactoLabe7;
    private javax.swing.JLabel tituloHogarLabel;
    private javax.swing.JLabel tituloPersonalesLabel;
    private javax.swing.JLabel tituloTrabajoLabel;
    private javax.swing.JLabel trabajoLabel;
    private javax.swing.JTextField trabajoTextField;
    private javax.swing.JLabel viviendaLabel;
    // End of variables declaration//GEN-END:variables
}
