/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InformeMedico;

/**
 *
 * @author munchi
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        pacienteOpcionMenu = new javax.swing.JMenu();
        datosPacienteMenuItem = new javax.swing.JMenuItem();
        nacimientoMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        historialSaludMenuItem = new javax.swing.JMenuItem();
        historialFamiliarMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        opcionInfoMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pacienteOpcionMenu.setText("Paciente");

        datosPacienteMenuItem.setText("Datos Paciente");
        datosPacienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosPacienteMenuItemActionPerformed(evt);
            }
        });
        pacienteOpcionMenu.add(datosPacienteMenuItem);

        nacimientoMenuItem1.setText("Nacimiento");
        nacimientoMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacimientoMenuItem1ActionPerformed(evt);
            }
        });
        pacienteOpcionMenu.add(nacimientoMenuItem1);

        jMenu4.setText("Historial");

        historialSaludMenuItem.setText("Historial de salud");
        jMenu4.add(historialSaludMenuItem);

        historialFamiliarMenuItem.setText("Historial familiar");
        jMenu4.add(historialFamiliarMenuItem);

        pacienteOpcionMenu.add(jMenu4);

        salirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        pacienteOpcionMenu.add(salirMenuItem);

        barraMenu.add(pacienteOpcionMenu);

        opcionInfoMenu.setText("Info");
        barraMenu.add(opcionInfoMenu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nacimientoMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacimientoMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacimientoMenuItem1ActionPerformed

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void datosPacienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosPacienteMenuItemActionPerformed
        DatosPaciente datosPaciente = new DatosPaciente();
        datosPaciente.setVisible(true);//abre la ventana
        datosPaciente.setLocationRelativeTo(null);//hace que La ventana salga Centrada
        this.dispose();//hace que la ventana se cierre al abirir la otra
    }//GEN-LAST:event_datosPacienteMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem datosPacienteMenuItem;
    private javax.swing.JMenuItem historialFamiliarMenuItem;
    private javax.swing.JMenuItem historialSaludMenuItem;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem nacimientoMenuItem1;
    private javax.swing.JMenu opcionInfoMenu;
    private javax.swing.JMenu pacienteOpcionMenu;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables
}
